export const AppCache = `app-todo`;

export const timeGreeting = [
    "Midnight",
    "Midnight",
    "Midnight",
    "Midnight",
    "Early Morning",
    "Early Morning",
    "Early Morning",
    "Morning",
    "Morning",
    "Morning",
    "Late Morning",
    "Late Morning",
    "Noon",
    "Noon",
    "Noon",
    "Evening",
    "Evening",
    "Evening",
    "Evening",
    "Night",
    "Night",
    "Night",
    "Late Night",
    "Late Night",
];
